# Generated by Django 4.2.1 on 2024-06-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
