# Generated by Django 4.2.1 on 2024-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorial_tutorial_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_url',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
